const ENV = {
  SUPABASE_URL: 'https://xqowmabashtmusjrovbt.supabase.co',
  SUPABASE_PUBLISHABLE_KEY: 'sb_publishable_5vwAk8Ec4SjL7Bv0QdIUGg_C9FDSTbi',
  PISTON_API_URL: 'https://emkc.org/api/v2/piston',
};

export const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, PISTON_API_URL } = ENV;

export const COLORS = {
  background: '#0a0a0a',
  surface: '#111111',
  surfaceLight: '#1a1a1a',
  surfaceDim: '#242424',
  primary: '#b0b0b0',
  primaryDark: '#888888',
  secondary: '#d0d0d0',
  accent: '#999999',
  success: '#3FB950',
  error: '#F85149',
  terminal: '#3FB950',
  prompt: '#58A6FF',
  text: '#d0d0d0',
  textSecondary: '#999999',
  textMuted: '#555555',
  border: '#222222',
  borderLight: '#2a2a2a',
  card: '#111111',
  inputBg: '#0a0a0a',
  navBg: 'rgba(10,10,10,0.85)',
};

export const FONTS = {
  regular: 'monospace',
  bold: 'monospace',
};

export const DIFFICULTY_COLORS = {
  beginner: '#3FB950',
  easy: '#58A6FF',
  medium: '#999999',
  hard: '#d0d0d0',
  expert: '#F85149',
};

export const RANKS = [
  { name: 'NOVICE', minXp: 0, color: '#555555' },
  { name: 'CODER', minXp: 1000, color: '#999999' },
  { name: 'DEVELOPER', minXp: 5000, color: '#b0b0b0' },
  { name: 'ENGINEER', minXp: 15000, color: '#58A6FF' },
  { name: 'ARCHITECT', minXp: 35000, color: '#BC8CFF' },
  { name: 'LEGEND', minXp: 70000, color: '#F85149' },
];

export const ICONS = {
  home: '~',
  courses: '[]',
  leaderboard: '##',
  profile: '@',
  back: '<',
  forward: '>',
  check: 'ok',
  fail: '!!',
  star: '*',
  xp: '+',
  lock: '##',
  code: '>_',
  terminal: '_>',
  lesson: '##',
  quiz: '?',
  challenge: '!',
  project: '{}',
  python: '>>>',
  javascript: '{/}',
  typescript: 'T>',
  rust: 'R>',
  go: 'GO',
  java: 'JV',
  cpp: 'C+',
  csharp: 'C#',
  ruby: 'RB',
  php: 'PH',
  bash: '$_',
  sql: 'SQ',
  r: 'R_',
  swift: 'SF',
  kotlin: 'KN',
  dart: 'DT',
  html: '<>',
  css: '#{}',
  user: '@',
  badge: '*',
  rank: '!',
  streak: '=',
  quest: '?',
  settings: '@@',
  create: '+',
  edit: '=/',
  publish: '>>',
  draft: '..',
  search: '/',
  filter: '|',
  module: '[]',
  lessonType: '##',
  completed: 'ok',
  pending: '..',
  xpIcon: '+',
  level: '[]',
  progress: '##',
};

export const EXERCISE_TYPES = [
  { id: 'lesson', label: 'LESSON' },
  { id: 'multiple_choice', label: 'CHOICE' },
  { id: 'true_false', label: 'BOOL' },
  { id: 'fill_blank', label: 'FILL' },
  { id: 'matching', label: 'MATCH' },
  { id: 'ordering', label: 'ORDER' },
  { id: 'output_prediction', label: 'PREDICT' },
  { id: 'code_completion', label: 'COMPLETE' },
  { id: 'code_challenge', label: 'CHALLENGE' },
  { id: 'parsons_problem', label: 'PARSONS' },
  { id: 'debug_challenge', label: 'DEBUG' },
  { id: 'code_review', label: 'REVIEW' },
  { id: 'sql_challenge', label: 'SQL' },
  { id: 'regex_challenge', label: 'REGEX' },
  { id: 'short_answer', label: 'WRITE' },
  { id: 'project', label: 'PROJECT' },
];
